// practica_logstash/src/main/webapp/app/entities/mensaje-privado/delete/mensaje-privado-delete-dialog.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { IMensajePrivado } from '../mensaje-privado.model';
import { MensajePrivadoService } from '../service/mensaje-privado.service';
import { ITEM_DELETED_EVENT } from 'app/config/navigation.constants';

@Component({
  templateUrl: './mensaje-privado-delete-dialog.component.html',
})
export class MensajePrivadoDeleteDialogComponent {
  mensajePrivado?: IMensajePrivado;

  constructor(protected mensajePrivadoService: MensajePrivadoService, protected activeModal: NgbActiveModal) {}

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.mensajePrivadoService.delete(id).subscribe(() => {
      this.activeModal.close(ITEM_DELETED_EVENT);
    });
  }
}

<form *ngIf="mensajePrivado" name="deleteForm" (ngSubmit)="confirmDelete(mensajePrivado.id!)">
  <div class="modal-header">
    <h4 class="modal-title" data-cy="mensajePrivadoDeleteDialogHeading" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

    <button type="button" class="btn-close" data-dismiss="modal" aria-hidden="true" (click)="cancel()">&times;</button>
  </div>

  <div class="modal-body">
    <jhi-alert-error></jhi-alert-error>
    <p
      id="jhi-delete-mensajePrivado-heading"
      jhiTranslate="microblogApp.mensajePrivado.delete.question"
      [translateValues]="{ id: mensajePrivado.id }"
    >
      Are you sure you want to delete Mensaje Privado {{ mensajePrivado.id }}?
    </p>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
      <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
    </button>

    <button id="jhi-confirm-delete-mensajePrivado" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
      <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
    </button>
  </div>
</form>

// Ionic_react/src/main/webapp/app/entities/mensaje-privado/mensaje-privado-delete-dialog.tsx
import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { getEntity, deleteEntity } from './mensaje-privado.reducer';

export const MensajePrivadoDeleteDialog = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();

  const [loadModal, setLoadModal] = useState(false);

  useEffect(() => {
    dispatch(getEntity(id));
    setLoadModal(true);
  }, []);

  const mensajePrivadoEntity = useAppSelector(state => state.mensajePrivado.entity);
  const updateSuccess = useAppSelector(state => state.mensajePrivado.updateSuccess);

  const handleClose = () => {
    navigate('/mensaje-privado');
  };

  useEffect(() => {
    if (updateSuccess && loadModal) {
      handleClose();
      setLoadModal(false);
    }
  }, [updateSuccess]);

  const confirmDelete = () => {
    dispatch(deleteEntity(mensajePrivadoEntity.id));
  };

  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="mensajePrivadoDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="microblogApp.mensajePrivado.delete.question">
        <Translate contentKey="microblogApp.mensajePrivado.delete.question" interpolate={{ id: mensajePrivadoEntity.id }}>
          Are you sure you want to delete this MensajePrivado?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-mensajePrivado" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export default MensajePrivadoDeleteDialog;
