// practica_logstash/src/main/webapp/app/entities/mensaje-privado/list/mensaje-privado.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router } from '@angular/router';
import { combineLatest, filter, Observable, switchMap, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IMensajePrivado } from '../mensaje-privado.model';
import { ASC, DESC, SORT, ITEM_DELETED_EVENT, DEFAULT_SORT_DATA } from 'app/config/navigation.constants';
import { EntityArrayResponseType, MensajePrivadoService } from '../service/mensaje-privado.service';
import { MensajePrivadoDeleteDialogComponent } from '../delete/mensaje-privado-delete-dialog.component';
import { SortService } from 'app/shared/sort/sort.service';

@Component({
  selector: 'jhi-mensaje-privado',
  templateUrl: './mensaje-privado.component.html',
})
export class MensajePrivadoComponent implements OnInit {
  mensajePrivados?: IMensajePrivado[];
  isLoading = false;

  predicate = 'id';
  ascending = true;

  constructor(
    protected mensajePrivadoService: MensajePrivadoService,
    protected activatedRoute: ActivatedRoute,
    public router: Router,
    protected sortService: SortService,
    protected modalService: NgbModal
  ) {}

  trackId = (_index: number, item: IMensajePrivado): number => this.mensajePrivadoService.getMensajePrivadoIdentifier(item);

  ngOnInit(): void {
    this.load();
  }

  delete(mensajePrivado: IMensajePrivado): void {
    const modalRef = this.modalService.open(MensajePrivadoDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.mensajePrivado = mensajePrivado;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        switchMap(() => this.loadFromBackendWithRouteInformations())
      )
      .subscribe({
        next: (res: EntityArrayResponseType) => {
          this.onResponseSuccess(res);
        },
      });
  }

  load(): void {
    this.loadFromBackendWithRouteInformations().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(): void {
    this.handleNavigation(this.predicate, this.ascending);
  }

  protected loadFromBackendWithRouteInformations(): Observable<EntityArrayResponseType> {
    return combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data]).pipe(
      tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
      switchMap(() => this.queryBackend(this.predicate, this.ascending))
    );
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const sort = (params.get(SORT) ?? data[DEFAULT_SORT_DATA]).split(',');
    this.predicate = sort[0];
    this.ascending = sort[1] === ASC;
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.mensajePrivados = this.refineData(dataFromBody);
  }

  protected refineData(data: IMensajePrivado[]): IMensajePrivado[] {
    return data.sort(this.sortService.startSort(this.predicate, this.ascending ? 1 : -1));
  }

  protected fillComponentAttributesFromResponseBody(data: IMensajePrivado[] | null): IMensajePrivado[] {
    return data ?? [];
  }

  protected queryBackend(predicate?: string, ascending?: boolean): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject = {
      eagerload: true,
      sort: this.getSortQueryParam(predicate, ascending),
    };
    return this.mensajePrivadoService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(predicate?: string, ascending?: boolean): void {
    const queryParamsObj = {
      sort: this.getSortQueryParam(predicate, ascending),
    };

    this.router.navigate(['./'], {
      relativeTo: this.activatedRoute,
      queryParams: queryParamsObj,
    });
  }

  protected getSortQueryParam(predicate = this.predicate, ascending = this.ascending): string[] {
    const ascendingQueryParam = ascending ? ASC : DESC;
    if (predicate === '') {
      return [];
    } else {
      return [predicate + ',' + ascendingQueryParam];
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="MensajePrivadoHeading">
    <span jhiTranslate="microblogApp.mensajePrivado.home.title">Mensaje Privados</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="microblogApp.mensajePrivado.home.refreshListLabel">Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-mensaje-privado"
        [routerLink]="['/mensaje-privado/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="microblogApp.mensajePrivado.home.createLabel"> Create a new Mensaje Privado </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="mensajePrivados?.length === 0">
    <span jhiTranslate="microblogApp.mensajePrivado.home.notFound">No Mensaje Privados found</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="mensajePrivados && mensajePrivados.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" jhiSortBy="id">
            <div class="d-flex">
              <span jhiTranslate="global.field.id">ID</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="texto">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.mensajePrivado.texto">Texto</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="fecha">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.mensajePrivado.fecha">Fecha</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="autor.alias">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.mensajePrivado.autor">Autor</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="destino.alias">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.mensajePrivado.destino">Destino</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let mensajePrivado of mensajePrivados; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/mensaje-privado', mensajePrivado.id, 'view']">{{ mensajePrivado.id }}</a>
          </td>
          <td>{{ mensajePrivado.texto }}</td>
          <td>{{ mensajePrivado.fecha | formatMediumDate }}</td>
          <td>
            <div *ngIf="mensajePrivado.autor">
              <a [routerLink]="['/usuario', mensajePrivado.autor.id, 'view']">{{ mensajePrivado.autor.alias }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="mensajePrivado.destino">
              <a [routerLink]="['/usuario', mensajePrivado.destino.id, 'view']">{{ mensajePrivado.destino.alias }}</a>
            </div>
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/mensaje-privado', mensajePrivado.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/mensaje-privado', mensajePrivado.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(mensajePrivado)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// Ionic_react/src/main/webapp/app/entities/mensaje-privado/mensaje-privado.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IMensajePrivado } from 'app/shared/model/mensaje-privado.model';
import { getEntities } from './mensaje-privado.reducer';

export const MensajePrivado = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();

  const mensajePrivadoList = useAppSelector(state => state.mensajePrivado.entities);
  const loading = useAppSelector(state => state.mensajePrivado.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  return (
    <div>
      <h2 id="mensaje-privado-heading" data-cy="MensajePrivadoHeading">
        <Translate contentKey="microblogApp.mensajePrivado.home.title">Mensaje Privados</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="microblogApp.mensajePrivado.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/mensaje-privado/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="microblogApp.mensajePrivado.home.createLabel">Create new Mensaje Privado</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {mensajePrivadoList && mensajePrivadoList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="microblogApp.mensajePrivado.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.mensajePrivado.texto">Texto</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.mensajePrivado.fecha">Fecha</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.mensajePrivado.autor">Autor</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.mensajePrivado.destino">Destino</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {mensajePrivadoList.map((mensajePrivado, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/mensaje-privado/${mensajePrivado.id}`} color="link" size="sm">
                      {mensajePrivado.id}
                    </Button>
                  </td>
                  <td>{mensajePrivado.texto}</td>
                  <td>
                    {mensajePrivado.fecha ? <TextFormat type="date" value={mensajePrivado.fecha} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td>
                    {mensajePrivado.autor ? <Link to={`/usuario/${mensajePrivado.autor.id}`}>{mensajePrivado.autor.alias}</Link> : ''}
                  </td>
                  <td>
                    {mensajePrivado.destino ? <Link to={`/usuario/${mensajePrivado.destino.id}`}>{mensajePrivado.destino.alias}</Link> : ''}
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/mensaje-privado/${mensajePrivado.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/mensaje-privado/${mensajePrivado.id}/edit`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/mensaje-privado/${mensajePrivado.id}/delete`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="microblogApp.mensajePrivado.home.notFound">No Mensaje Privados found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default MensajePrivado;
