// Ionic_react/src/main/webapp/app/entities/mensaje/mensaje-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './mensaje.reducer';

export const MensajeDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const mensajeEntity = useAppSelector(state => state.mensaje.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="mensajeDetailsHeading">
          <Translate contentKey="microblogApp.mensaje.detail.title">Mensaje</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{mensajeEntity.id}</dd>
          <dt>
            <span id="texto">
              <Translate contentKey="microblogApp.mensaje.texto">Texto</Translate>
            </span>
          </dt>
          <dd>{mensajeEntity.texto}</dd>
          <dt>
            <span id="fecha">
              <Translate contentKey="microblogApp.mensaje.fecha">Fecha</Translate>
            </span>
          </dt>
          <dd>{mensajeEntity.fecha ? <TextFormat value={mensajeEntity.fecha} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}</dd>
          <dt>
            <Translate contentKey="microblogApp.mensaje.autor">Autor</Translate>
          </dt>
          <dd>{mensajeEntity.autor ? mensajeEntity.autor.alias : ''}</dd>
        </dl>
        <Button tag={Link} to="/mensaje" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/mensaje/${mensajeEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default MensajeDetail;

// practica_JDL/src/main/webapp/app/entities/mensaje/detail/mensaje-detail.component.ts
import { Component, Input } from '@angular/core';
import { ActivatedRoute, RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { IMensaje } from '../mensaje.model';

@Component({
  standalone: true,
  selector: 'jhi-mensaje-detail',
  templateUrl: './mensaje-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class MensajeDetailComponent {
  @Input() mensaje: IMensaje | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="mensaje">
      <h2 data-cy="mensajeDetailsHeading">
        <span jhiTranslate="jhLogstashApp.mensaje.detail.title">__jhiTransformTranslate__('jhLogstashApp.mensaje.detail.title')</span>
      </h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">__jhiTransformTranslate__('global.field.id')</span></dt>
        <dd>
          <span>{{ mensaje.id }}</span>
        </dd>
        <dt><span jhiTranslate="jhLogstashApp.mensaje.autor">__jhiTransformTranslate__('jhLogstashApp.mensaje.autor')</span></dt>
        <dd>
          <span>{{ mensaje.autor }}</span>
        </dd>
        <dt>
          <span jhiTranslate="jhLogstashApp.mensaje.fechaPublicacion"
            >__jhiTransformTranslate__('jhLogstashApp.mensaje.fechaPublicacion')</span
          >
        </dt>
        <dd>
          <span>{{ mensaje.fechaPublicacion | formatMediumDatetime }}</span>
        </dd>
        <dt>
          <span jhiTranslate="jhLogstashApp.mensaje.textoMensaje">__jhiTransformTranslate__('jhLogstashApp.mensaje.textoMensaje')</span>
        </dt>
        <dd>
          <span>{{ mensaje.textoMensaje }}</span>
        </dd>
        <dt><span jhiTranslate="jhLogstashApp.mensaje.etiquetas">__jhiTransformTranslate__('jhLogstashApp.mensaje.etiquetas')</span></dt>
        <dd>
          <span>{{ mensaje.etiquetas }}</span>
        </dd>
        <dt><span jhiTranslate="jhLogstashApp.mensaje.autor">__jhiTransformTranslate__('jhLogstashApp.mensaje.autor')</span></dt>
        <dd>
          <div *ngIf="mensaje.autor">
            <a [routerLink]="['/usuario', mensaje.autor.id, 'view']">{{ mensaje.autor.id }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="jhLogstashApp.mensaje.etiquetas">__jhiTransformTranslate__('jhLogstashApp.mensaje.etiquetas')</span></dt>
        <dd>
          <span *ngFor="let etiquetas of mensaje.etiquetas; let last = last">
            <a [routerLink]="['/etiqueta', etiquetas.id, 'view']">{{ etiquetas.id }}</a
            >{{ last ? '' : ', ' }}
          </span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"
          >__jhiTransformTranslate__('entity.action.back')</span
        >
      </button>

      <button type="button" [routerLink]="['/mensaje', mensaje.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"
          >__jhiTransformTranslate__('entity.action.edit')</span
        >
      </button>
    </div>
  </div>
</div>
