// Ionic_react/src/main/webapp/app/entities/mensaje-privado/mensaje-privado-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './mensaje-privado.reducer';

export const MensajePrivadoDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const mensajePrivadoEntity = useAppSelector(state => state.mensajePrivado.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="mensajePrivadoDetailsHeading">
          <Translate contentKey="microblogApp.mensajePrivado.detail.title">MensajePrivado</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{mensajePrivadoEntity.id}</dd>
          <dt>
            <span id="texto">
              <Translate contentKey="microblogApp.mensajePrivado.texto">Texto</Translate>
            </span>
          </dt>
          <dd>{mensajePrivadoEntity.texto}</dd>
          <dt>
            <span id="fecha">
              <Translate contentKey="microblogApp.mensajePrivado.fecha">Fecha</Translate>
            </span>
          </dt>
          <dd>
            {mensajePrivadoEntity.fecha ? (
              <TextFormat value={mensajePrivadoEntity.fecha} type="date" format={APP_LOCAL_DATE_FORMAT} />
            ) : null}
          </dd>
          <dt>
            <Translate contentKey="microblogApp.mensajePrivado.autor">Autor</Translate>
          </dt>
          <dd>{mensajePrivadoEntity.autor ? mensajePrivadoEntity.autor.alias : ''}</dd>
          <dt>
            <Translate contentKey="microblogApp.mensajePrivado.destino">Destino</Translate>
          </dt>
          <dd>{mensajePrivadoEntity.destino ? mensajePrivadoEntity.destino.alias : ''}</dd>
        </dl>
        <Button tag={Link} to="/mensaje-privado" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/mensaje-privado/${mensajePrivadoEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default MensajePrivadoDetail;

// practica_logstash/src/main/webapp/app/entities/mensaje-privado/detail/mensaje-privado-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IMensajePrivado } from '../mensaje-privado.model';

@Component({
  selector: 'jhi-mensaje-privado-detail',
  templateUrl: './mensaje-privado-detail.component.html',
})
export class MensajePrivadoDetailComponent implements OnInit {
  mensajePrivado: IMensajePrivado | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ mensajePrivado }) => {
      this.mensajePrivado = mensajePrivado;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="mensajePrivado">
      <h2 data-cy="mensajePrivadoDetailsHeading"><span jhiTranslate="microblogApp.mensajePrivado.detail.title">Mensaje Privado</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ mensajePrivado.id }}</span>
        </dd>
        <dt><span jhiTranslate="microblogApp.mensajePrivado.texto">Texto</span></dt>
        <dd>
          <span>{{ mensajePrivado.texto }}</span>
        </dd>
        <dt><span jhiTranslate="microblogApp.mensajePrivado.fecha">Fecha</span></dt>
        <dd>
          <span>{{ mensajePrivado.fecha | formatMediumDate }}</span>
        </dd>
        <dt><span jhiTranslate="microblogApp.mensajePrivado.autor">Autor</span></dt>
        <dd>
          <div *ngIf="mensajePrivado.autor">
            <a [routerLink]="['/usuario', mensajePrivado.autor.id, 'view']">{{ mensajePrivado.autor.alias }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="microblogApp.mensajePrivado.destino">Destino</span></dt>
        <dd>
          <div *ngIf="mensajePrivado.destino">
            <a [routerLink]="['/usuario', mensajePrivado.destino.id, 'view']">{{ mensajePrivado.destino.alias }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/mensaje-privado', mensajePrivado.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>
