// Ionic_react/src/main/webapp/app/entities/mensaje/mensaje-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './mensaje.reducer';

export const MensajeDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const mensajeEntity = useAppSelector(state => state.mensaje.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="mensajeDetailsHeading">
          <Translate contentKey="microblogApp.mensaje.detail.title">Mensaje</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{mensajeEntity.id}</dd>
          <dt>
            <span id="texto">
              <Translate contentKey="microblogApp.mensaje.texto">Texto</Translate>
            </span>
          </dt>
          <dd>{mensajeEntity.texto}</dd>
          <dt>
            <span id="fecha">
              <Translate contentKey="microblogApp.mensaje.fecha">Fecha</Translate>
            </span>
          </dt>
          <dd>{mensajeEntity.fecha ? <TextFormat value={mensajeEntity.fecha} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}</dd>
          <dt>
            <Translate contentKey="microblogApp.mensaje.autor">Autor</Translate>
          </dt>
          <dd>{mensajeEntity.autor ? mensajeEntity.autor.alias : ''}</dd>
        </dl>
        <Button tag={Link} to="/mensaje" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/mensaje/${mensajeEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default MensajeDetail;

// practica_logstash/src/main/webapp/app/entities/mensaje/detail/mensaje-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IMensaje } from '../mensaje.model';

@Component({
  selector: 'jhi-mensaje-detail',
  templateUrl: './mensaje-detail.component.html',
})
export class MensajeDetailComponent implements OnInit {
  mensaje: IMensaje | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ mensaje }) => {
      this.mensaje = mensaje;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="mensaje">
      <h2 data-cy="mensajeDetailsHeading"><span jhiTranslate="microblogApp.mensaje.detail.title">Mensaje</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ mensaje.id }}</span>
        </dd>
        <dt><span jhiTranslate="microblogApp.mensaje.texto">Texto</span></dt>
        <dd>
          <span>{{ mensaje.texto }}</span>
        </dd>
        <dt><span jhiTranslate="microblogApp.mensaje.fecha">Fecha</span></dt>
        <dd>
          <span>{{ mensaje.fecha | formatMediumDate }}</span>
        </dd>
        <dt><span jhiTranslate="microblogApp.mensaje.autor">Autor</span></dt>
        <dd>
          <div *ngIf="mensaje.autor">
            <a [routerLink]="['/usuario', mensaje.autor.id, 'view']">{{ mensaje.autor.alias }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/mensaje', mensaje.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>
