// Ionic_react/src/main/webapp/app/entities/mensaje-privado/mensaje-privado-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IUsuario } from 'app/shared/model/usuario.model';
import { getEntities as getUsuarios } from 'app/entities/usuario/usuario.reducer';
import { IMensajePrivado } from 'app/shared/model/mensaje-privado.model';
import { getEntity, updateEntity, createEntity, reset } from './mensaje-privado.reducer';

export const MensajePrivadoUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const usuarios = useAppSelector(state => state.usuario.entities);
  const mensajePrivadoEntity = useAppSelector(state => state.mensajePrivado.entity);
  const loading = useAppSelector(state => state.mensajePrivado.loading);
  const updating = useAppSelector(state => state.mensajePrivado.updating);
  const updateSuccess = useAppSelector(state => state.mensajePrivado.updateSuccess);

  const handleClose = () => {
    navigate('/mensaje-privado');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getUsuarios({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    const entity = {
      ...mensajePrivadoEntity,
      ...values,
      autor: usuarios.find(it => it.id.toString() === values.autor.toString()),
      destino: usuarios.find(it => it.id.toString() === values.destino.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          ...mensajePrivadoEntity,
          autor: mensajePrivadoEntity?.autor?.id,
          destino: mensajePrivadoEntity?.destino?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="microblogApp.mensajePrivado.home.createOrEditLabel" data-cy="MensajePrivadoCreateUpdateHeading">
            <Translate contentKey="microblogApp.mensajePrivado.home.createOrEditLabel">Create or edit a MensajePrivado</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="mensaje-privado-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('microblogApp.mensajePrivado.texto')}
                id="mensaje-privado-texto"
                name="texto"
                data-cy="texto"
                type="text"
              />
              <ValidatedField
                label={translate('microblogApp.mensajePrivado.fecha')}
                id="mensaje-privado-fecha"
                name="fecha"
                data-cy="fecha"
                type="date"
              />
              <ValidatedField
                id="mensaje-privado-autor"
                name="autor"
                data-cy="autor"
                label={translate('microblogApp.mensajePrivado.autor')}
                type="select"
              >
                <option value="" key="0" />
                {usuarios
                  ? usuarios.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.alias}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField
                id="mensaje-privado-destino"
                name="destino"
                data-cy="destino"
                label={translate('microblogApp.mensajePrivado.destino')}
                type="select"
              >
                <option value="" key="0" />
                {usuarios
                  ? usuarios.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.alias}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/mensaje-privado" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default MensajePrivadoUpdate;

// practica_logstash/src/main/webapp/app/entities/mensaje-privado/update/mensaje-privado-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { MensajePrivadoFormService, MensajePrivadoFormGroup } from './mensaje-privado-form.service';
import { IMensajePrivado } from '../mensaje-privado.model';
import { MensajePrivadoService } from '../service/mensaje-privado.service';
import { IUsuario } from 'app/entities/usuario/usuario.model';
import { UsuarioService } from 'app/entities/usuario/service/usuario.service';

@Component({
  selector: 'jhi-mensaje-privado-update',
  templateUrl: './mensaje-privado-update.component.html',
})
export class MensajePrivadoUpdateComponent implements OnInit {
  isSaving = false;
  mensajePrivado: IMensajePrivado | null = null;

  autorsCollection: IUsuario[] = [];
  destinosCollection: IUsuario[] = [];

  editForm: MensajePrivadoFormGroup = this.mensajePrivadoFormService.createMensajePrivadoFormGroup();

  constructor(
    protected mensajePrivadoService: MensajePrivadoService,
    protected mensajePrivadoFormService: MensajePrivadoFormService,
    protected usuarioService: UsuarioService,
    protected activatedRoute: ActivatedRoute
  ) {}

  compareUsuario = (o1: IUsuario | null, o2: IUsuario | null): boolean => this.usuarioService.compareUsuario(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ mensajePrivado }) => {
      this.mensajePrivado = mensajePrivado;
      if (mensajePrivado) {
        this.updateForm(mensajePrivado);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const mensajePrivado = this.mensajePrivadoFormService.getMensajePrivado(this.editForm);
    if (mensajePrivado.id !== null) {
      this.subscribeToSaveResponse(this.mensajePrivadoService.update(mensajePrivado));
    } else {
      this.subscribeToSaveResponse(this.mensajePrivadoService.create(mensajePrivado));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IMensajePrivado>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(mensajePrivado: IMensajePrivado): void {
    this.mensajePrivado = mensajePrivado;
    this.mensajePrivadoFormService.resetForm(this.editForm, mensajePrivado);

    this.autorsCollection = this.usuarioService.addUsuarioToCollectionIfMissing<IUsuario>(this.autorsCollection, mensajePrivado.autor);
    this.destinosCollection = this.usuarioService.addUsuarioToCollectionIfMissing<IUsuario>(
      this.destinosCollection,
      mensajePrivado.destino
    );
  }

  protected loadRelationshipsOptions(): void {
    this.usuarioService
      .query({ filter: 'mensajeprivadoenviado-is-null' })
      .pipe(map((res: HttpResponse<IUsuario[]>) => res.body ?? []))
      .pipe(
        map((usuarios: IUsuario[]) => this.usuarioService.addUsuarioToCollectionIfMissing<IUsuario>(usuarios, this.mensajePrivado?.autor))
      )
      .subscribe((usuarios: IUsuario[]) => (this.autorsCollection = usuarios));

    this.usuarioService
      .query({ filter: 'mensajeprivadorecibido-is-null' })
      .pipe(map((res: HttpResponse<IUsuario[]>) => res.body ?? []))
      .pipe(
        map((usuarios: IUsuario[]) => this.usuarioService.addUsuarioToCollectionIfMissing<IUsuario>(usuarios, this.mensajePrivado?.destino))
      )
      .subscribe((usuarios: IUsuario[]) => (this.destinosCollection = usuarios));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-mensaje-privado-heading"
        data-cy="MensajePrivadoCreateUpdateHeading"
        jhiTranslate="microblogApp.mensajePrivado.home.createOrEditLabel"
      >
        Create or edit a Mensaje Privado
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="row mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.mensajePrivado.texto" for="field_texto">Texto</label>
          <input type="text" class="form-control" name="texto" id="field_texto" data-cy="texto" formControlName="texto" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.mensajePrivado.fecha" for="field_fecha">Fecha</label>
          <div class="input-group">
            <input
              id="field_fecha"
              data-cy="fecha"
              type="text"
              class="form-control"
              name="fecha"
              ngbDatepicker
              #fechaDp="ngbDatepicker"
              formControlName="fecha"
            />
            <button type="button" class="btn btn-secondary" (click)="fechaDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
          </div>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.mensajePrivado.autor" for="field_autor">Autor</label>
          <select class="form-control" id="field_autor" data-cy="autor" name="autor" formControlName="autor" [compareWith]="compareUsuario">
            <option [ngValue]="null"></option>
            <option [ngValue]="usuarioOption" *ngFor="let usuarioOption of autorsCollection">{{ usuarioOption.alias }}</option>
          </select>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.mensajePrivado.destino" for="field_destino">Destino</label>
          <select
            class="form-control"
            id="field_destino"
            data-cy="destino"
            name="destino"
            formControlName="destino"
            [compareWith]="compareUsuario"
          >
            <option [ngValue]="null"></option>
            <option [ngValue]="usuarioOption" *ngFor="let usuarioOption of destinosCollection">{{ usuarioOption.alias }}</option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
