// practica_logstash/src/main/webapp/app/entities/usuario/update/usuario-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { UsuarioFormService, UsuarioFormGroup } from './usuario-form.service';
import { IUsuario } from '../usuario.model';
import { UsuarioService } from '../service/usuario.service';
import { IMensaje } from 'app/entities/mensaje/mensaje.model';
import { MensajeService } from 'app/entities/mensaje/service/mensaje.service';

@Component({
  selector: 'jhi-usuario-update',
  templateUrl: './usuario-update.component.html',
})
export class UsuarioUpdateComponent implements OnInit {
  isSaving = false;
  usuario: IUsuario | null = null;

  usuariosSharedCollection: IUsuario[] = [];
  mensajesSharedCollection: IMensaje[] = [];

  editForm: UsuarioFormGroup = this.usuarioFormService.createUsuarioFormGroup();

  constructor(
    protected usuarioService: UsuarioService,
    protected usuarioFormService: UsuarioFormService,
    protected mensajeService: MensajeService,
    protected activatedRoute: ActivatedRoute
  ) {}

  compareUsuario = (o1: IUsuario | null, o2: IUsuario | null): boolean => this.usuarioService.compareUsuario(o1, o2);

  compareMensaje = (o1: IMensaje | null, o2: IMensaje | null): boolean => this.mensajeService.compareMensaje(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ usuario }) => {
      this.usuario = usuario;
      if (usuario) {
        this.updateForm(usuario);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const usuario = this.usuarioFormService.getUsuario(this.editForm);
    if (usuario.id !== null) {
      this.subscribeToSaveResponse(this.usuarioService.update(usuario));
    } else {
      this.subscribeToSaveResponse(this.usuarioService.create(usuario));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IUsuario>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(usuario: IUsuario): void {
    this.usuario = usuario;
    this.usuarioFormService.resetForm(this.editForm, usuario);

    this.usuariosSharedCollection = this.usuarioService.addUsuarioToCollectionIfMissing<IUsuario>(
      this.usuariosSharedCollection,
      ...(usuario.siguiendos ?? [])
    );
    this.mensajesSharedCollection = this.mensajeService.addMensajeToCollectionIfMissing<IMensaje>(
      this.mensajesSharedCollection,
      usuario.mensajeMencionado
    );
  }

  protected loadRelationshipsOptions(): void {
    this.usuarioService
      .query()
      .pipe(map((res: HttpResponse<IUsuario[]>) => res.body ?? []))
      .pipe(
        map((usuarios: IUsuario[]) =>
          this.usuarioService.addUsuarioToCollectionIfMissing<IUsuario>(usuarios, ...(this.usuario?.siguiendos ?? []))
        )
      )
      .subscribe((usuarios: IUsuario[]) => (this.usuariosSharedCollection = usuarios));

    this.mensajeService
      .query()
      .pipe(map((res: HttpResponse<IMensaje[]>) => res.body ?? []))
      .pipe(
        map((mensajes: IMensaje[]) =>
          this.mensajeService.addMensajeToCollectionIfMissing<IMensaje>(mensajes, this.usuario?.mensajeMencionado)
        )
      )
      .subscribe((mensajes: IMensaje[]) => (this.mensajesSharedCollection = mensajes));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-usuario-heading" data-cy="UsuarioCreateUpdateHeading" jhiTranslate="microblogApp.usuario.home.createOrEditLabel">
        Create or edit a Usuario
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="row mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.usuario.alias" for="field_alias">Alias</label>
          <input type="text" class="form-control" name="alias" id="field_alias" data-cy="alias" formControlName="alias" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.usuario.nombre" for="field_nombre">Nombre</label>
          <input type="text" class="form-control" name="nombre" id="field_nombre" data-cy="nombre" formControlName="nombre" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.usuario.correo" for="field_correo">Correo</label>
          <input type="text" class="form-control" name="correo" id="field_correo" data-cy="correo" formControlName="correo" />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.usuario.contrasenia" for="field_contrasenia">Contrasenia</label>
          <input
            type="text"
            class="form-control"
            name="contrasenia"
            id="field_contrasenia"
            data-cy="contrasenia"
            formControlName="contrasenia"
          />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.usuario.descripcion" for="field_descripcion">Descripcion</label>
          <input
            type="text"
            class="form-control"
            name="descripcion"
            id="field_descripcion"
            data-cy="descripcion"
            formControlName="descripcion"
          />
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.usuario.admin" for="field_admin">Admin</label>
          <input type="checkbox" class="form-check" name="admin" id="field_admin" data-cy="admin" formControlName="admin" />
        </div>

        <div class="row mb-3">
          <label jhiTranslate="microblogApp.usuario.siguiendo" for="field_siguiendos">Siguiendo</label>
          <select
            class="form-control"
            id="field_siguiendos"
            data-cy="siguiendo"
            multiple
            name="siguiendos"
            formControlName="siguiendos"
            [compareWith]="compareUsuario"
          >
            <option [ngValue]="usuarioOption" *ngFor="let usuarioOption of usuariosSharedCollection">{{ usuarioOption.id }}</option>
          </select>
        </div>

        <div class="row mb-3">
          <label class="form-label" jhiTranslate="microblogApp.usuario.mensajeMencionado" for="field_mensajeMencionado"
            >Mensaje Mencionado</label
          >
          <select
            class="form-control"
            id="field_mensajeMencionado"
            data-cy="mensajeMencionado"
            name="mensajeMencionado"
            formControlName="mensajeMencionado"
            [compareWith]="compareMensaje"
          >
            <option [ngValue]="null"></option>
            <option [ngValue]="mensajeOption" *ngFor="let mensajeOption of mensajesSharedCollection">{{ mensajeOption.id }}</option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// Ionic_react/src/main/webapp/app/entities/usuario/usuario-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntities as getUsuarios } from 'app/entities/usuario/usuario.reducer';
import { IMensaje } from 'app/shared/model/mensaje.model';
import { getEntities as getMensajes } from 'app/entities/mensaje/mensaje.reducer';
import { IMensajePrivado } from 'app/shared/model/mensaje-privado.model';
import { getEntities as getMensajePrivados } from 'app/entities/mensaje-privado/mensaje-privado.reducer';
import { IUsuario } from 'app/shared/model/usuario.model';
import { getEntity, updateEntity, createEntity, reset } from './usuario.reducer';

export const UsuarioUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const usuarios = useAppSelector(state => state.usuario.entities);
  const mensajes = useAppSelector(state => state.mensaje.entities);
  const mensajePrivados = useAppSelector(state => state.mensajePrivado.entities);
  const usuarioEntity = useAppSelector(state => state.usuario.entity);
  const loading = useAppSelector(state => state.usuario.loading);
  const updating = useAppSelector(state => state.usuario.updating);
  const updateSuccess = useAppSelector(state => state.usuario.updateSuccess);

  const handleClose = () => {
    navigate('/usuario');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getUsuarios({}));
    dispatch(getMensajes({}));
    dispatch(getMensajePrivados({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    const entity = {
      ...usuarioEntity,
      ...values,
      siguiendos: mapIdList(values.siguiendos),
      mensajeMencionado: mensajes.find(it => it.id.toString() === values.mensajeMencionado.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          ...usuarioEntity,
          siguiendos: usuarioEntity?.siguiendos?.map(e => e.id.toString()),
          mensajeMencionado: usuarioEntity?.mensajeMencionado?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="microblogApp.usuario.home.createOrEditLabel" data-cy="UsuarioCreateUpdateHeading">
            <Translate contentKey="microblogApp.usuario.home.createOrEditLabel">Create or edit a Usuario</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="usuario-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField label={translate('microblogApp.usuario.alias')} id="usuario-alias" name="alias" data-cy="alias" type="text" />
              <ValidatedField
                label={translate('microblogApp.usuario.nombre')}
                id="usuario-nombre"
                name="nombre"
                data-cy="nombre"
                type="text"
              />
              <ValidatedField
                label={translate('microblogApp.usuario.correo')}
                id="usuario-correo"
                name="correo"
                data-cy="correo"
                type="text"
              />
              <ValidatedField
                label={translate('microblogApp.usuario.contrasenia')}
                id="usuario-contrasenia"
                name="contrasenia"
                data-cy="contrasenia"
                type="text"
              />
              <ValidatedField
                label={translate('microblogApp.usuario.descripcion')}
                id="usuario-descripcion"
                name="descripcion"
                data-cy="descripcion"
                type="text"
              />
              <ValidatedField
                label={translate('microblogApp.usuario.admin')}
                id="usuario-admin"
                name="admin"
                data-cy="admin"
                check
                type="checkbox"
              />
              <ValidatedField
                label={translate('microblogApp.usuario.siguiendo')}
                id="usuario-siguiendo"
                data-cy="siguiendo"
                type="select"
                multiple
                name="siguiendos"
              >
                <option value="" key="0" />
                {usuarios
                  ? usuarios.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField
                id="usuario-mensajeMencionado"
                name="mensajeMencionado"
                data-cy="mensajeMencionado"
                label={translate('microblogApp.usuario.mensajeMencionado')}
                type="select"
              >
                <option value="" key="0" />
                {mensajes
                  ? mensajes.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/usuario" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default UsuarioUpdate;
