// practica_logstash/src/main/webapp/app/entities/usuario/list/usuario.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router } from '@angular/router';
import { combineLatest, filter, Observable, switchMap, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IUsuario } from '../usuario.model';
import { ASC, DESC, SORT, ITEM_DELETED_EVENT, DEFAULT_SORT_DATA } from 'app/config/navigation.constants';
import { EntityArrayResponseType, UsuarioService } from '../service/usuario.service';
import { UsuarioDeleteDialogComponent } from '../delete/usuario-delete-dialog.component';
import { SortService } from 'app/shared/sort/sort.service';

@Component({
  selector: 'jhi-usuario',
  templateUrl: './usuario.component.html',
})
export class UsuarioComponent implements OnInit {
  usuarios?: IUsuario[];
  isLoading = false;

  predicate = 'id';
  ascending = true;

  constructor(
    protected usuarioService: UsuarioService,
    protected activatedRoute: ActivatedRoute,
    public router: Router,
    protected sortService: SortService,
    protected modalService: NgbModal
  ) {}

  trackId = (_index: number, item: IUsuario): number => this.usuarioService.getUsuarioIdentifier(item);

  ngOnInit(): void {
    this.load();
  }

  delete(usuario: IUsuario): void {
    const modalRef = this.modalService.open(UsuarioDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.usuario = usuario;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        switchMap(() => this.loadFromBackendWithRouteInformations())
      )
      .subscribe({
        next: (res: EntityArrayResponseType) => {
          this.onResponseSuccess(res);
        },
      });
  }

  load(): void {
    this.loadFromBackendWithRouteInformations().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(): void {
    this.handleNavigation(this.predicate, this.ascending);
  }

  protected loadFromBackendWithRouteInformations(): Observable<EntityArrayResponseType> {
    return combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data]).pipe(
      tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
      switchMap(() => this.queryBackend(this.predicate, this.ascending))
    );
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const sort = (params.get(SORT) ?? data[DEFAULT_SORT_DATA]).split(',');
    this.predicate = sort[0];
    this.ascending = sort[1] === ASC;
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.usuarios = this.refineData(dataFromBody);
  }

  protected refineData(data: IUsuario[]): IUsuario[] {
    return data.sort(this.sortService.startSort(this.predicate, this.ascending ? 1 : -1));
  }

  protected fillComponentAttributesFromResponseBody(data: IUsuario[] | null): IUsuario[] {
    return data ?? [];
  }

  protected queryBackend(predicate?: string, ascending?: boolean): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject = {
      eagerload: true,
      sort: this.getSortQueryParam(predicate, ascending),
    };
    return this.usuarioService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(predicate?: string, ascending?: boolean): void {
    const queryParamsObj = {
      sort: this.getSortQueryParam(predicate, ascending),
    };

    this.router.navigate(['./'], {
      relativeTo: this.activatedRoute,
      queryParams: queryParamsObj,
    });
  }

  protected getSortQueryParam(predicate = this.predicate, ascending = this.ascending): string[] {
    const ascendingQueryParam = ascending ? ASC : DESC;
    if (predicate === '') {
      return [];
    } else {
      return [predicate + ',' + ascendingQueryParam];
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="UsuarioHeading">
    <span jhiTranslate="microblogApp.usuario.home.title">Usuarios</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="microblogApp.usuario.home.refreshListLabel">Refresh list</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-usuario"
        [routerLink]="['/usuario/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="microblogApp.usuario.home.createLabel"> Create a new Usuario </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="usuarios?.length === 0">
    <span jhiTranslate="microblogApp.usuario.home.notFound">No Usuarios found</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="usuarios && usuarios.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" jhiSortBy="id">
            <div class="d-flex">
              <span jhiTranslate="global.field.id">ID</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="alias">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.usuario.alias">Alias</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="nombre">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.usuario.nombre">Nombre</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="correo">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.usuario.correo">Correo</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="contrasenia">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.usuario.contrasenia">Contrasenia</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="descripcion">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.usuario.descripcion">Descripcion</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="admin">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.usuario.admin">Admin</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="siguiendo.id">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.usuario.siguiendo">Siguiendo</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="mensajeMencionado.id">
            <div class="d-flex">
              <span jhiTranslate="microblogApp.usuario.mensajeMencionado">Mensaje Mencionado</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let usuario of usuarios; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/usuario', usuario.id, 'view']">{{ usuario.id }}</a>
          </td>
          <td>{{ usuario.alias }}</td>
          <td>{{ usuario.nombre }}</td>
          <td>{{ usuario.correo }}</td>
          <td>{{ usuario.contrasenia }}</td>
          <td>{{ usuario.descripcion }}</td>
          <td>{{ usuario.admin }}</td>
          <td>
            <span *ngFor="let siguiendo of usuario.siguiendos; let last = last">
              <a class="form-control-static" [routerLink]="['/usuario', siguiendo.id, 'view']">{{ siguiendo.id }}</a
              >{{ last ? '' : ', ' }}
            </span>
          </td>
          <td>
            <div *ngIf="usuario.mensajeMencionado">
              <a [routerLink]="['/mensaje', usuario.mensajeMencionado.id, 'view']">{{ usuario.mensajeMencionado.id }}</a>
            </div>
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/usuario', usuario.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/usuario', usuario.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(usuario)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// Ionic_react/src/main/webapp/app/entities/usuario/usuario.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IUsuario } from 'app/shared/model/usuario.model';
import { getEntities } from './usuario.reducer';

export const Usuario = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();

  const usuarioList = useAppSelector(state => state.usuario.entities);
  const loading = useAppSelector(state => state.usuario.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  return (
    <div>
      <h2 id="usuario-heading" data-cy="UsuarioHeading">
        <Translate contentKey="microblogApp.usuario.home.title">Usuarios</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="microblogApp.usuario.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/usuario/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="microblogApp.usuario.home.createLabel">Create new Usuario</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {usuarioList && usuarioList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="microblogApp.usuario.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.usuario.alias">Alias</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.usuario.nombre">Nombre</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.usuario.correo">Correo</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.usuario.contrasenia">Contrasenia</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.usuario.descripcion">Descripcion</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.usuario.admin">Admin</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.usuario.siguiendo">Siguiendo</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.usuario.mensajeMencionado">Mensaje Mencionado</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {usuarioList.map((usuario, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/usuario/${usuario.id}`} color="link" size="sm">
                      {usuario.id}
                    </Button>
                  </td>
                  <td>{usuario.alias}</td>
                  <td>{usuario.nombre}</td>
                  <td>{usuario.correo}</td>
                  <td>{usuario.contrasenia}</td>
                  <td>{usuario.descripcion}</td>
                  <td>{usuario.admin ? 'true' : 'false'}</td>
                  <td>
                    {usuario.siguiendos
                      ? usuario.siguiendos.map((val, j) => (
                          <span key={j}>
                            <Link to={`/usuario/${val.id}`}>{val.id}</Link>
                            {j === usuario.siguiendos.length - 1 ? '' : ', '}
                          </span>
                        ))
                      : null}
                  </td>
                  <td>
                    {usuario.mensajeMencionado ? (
                      <Link to={`/mensaje/${usuario.mensajeMencionado.id}`}>{usuario.mensajeMencionado.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/usuario/${usuario.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/usuario/${usuario.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/usuario/${usuario.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="microblogApp.usuario.home.notFound">No Usuarios found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Usuario;
