// Ionic_react/src/main/webapp/app/entities/mensaje/mensaje.tsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IMensaje } from 'app/shared/model/mensaje.model';
import { getEntities } from './mensaje.reducer';

export const Mensaje = () => {
  const dispatch = useAppDispatch();

  const location = useLocation();
  const navigate = useNavigate();

  const mensajeList = useAppSelector(state => state.mensaje.entities);
  const loading = useAppSelector(state => state.mensaje.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  return (
    <div>
      <h2 id="mensaje-heading" data-cy="MensajeHeading">
        <Translate contentKey="microblogApp.mensaje.home.title">Mensajes</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="microblogApp.mensaje.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/mensaje/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="microblogApp.mensaje.home.createLabel">Create new Mensaje</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {mensajeList && mensajeList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="microblogApp.mensaje.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.mensaje.texto">Texto</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.mensaje.fecha">Fecha</Translate>
                </th>
                <th>
                  <Translate contentKey="microblogApp.mensaje.autor">Autor</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {mensajeList.map((mensaje, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/mensaje/${mensaje.id}`} color="link" size="sm">
                      {mensaje.id}
                    </Button>
                  </td>
                  <td>{mensaje.texto}</td>
                  <td>{mensaje.fecha ? <TextFormat type="date" value={mensaje.fecha} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>{mensaje.autor ? <Link to={`/usuario/${mensaje.autor.id}`}>{mensaje.autor.alias}</Link> : ''}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/mensaje/${mensaje.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/mensaje/${mensaje.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/mensaje/${mensaje.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="microblogApp.mensaje.home.notFound">No Mensajes found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Mensaje;

// practica_JDL/src/main/webapp/app/entities/mensaje/list/mensaje.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Data, ParamMap, Router, RouterModule } from '@angular/router';
import { combineLatest, filter, Observable, switchMap, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { SortDirective, SortByDirective } from 'app/shared/sort';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { FormsModule } from '@angular/forms';
import { ASC, DESC, SORT, ITEM_DELETED_EVENT, DEFAULT_SORT_DATA } from 'app/config/navigation.constants';
import { SortService } from 'app/shared/sort/sort.service';
import { IMensaje } from '../mensaje.model';
import { EntityArrayResponseType, MensajeService } from '../service/mensaje.service';
import { MensajeDeleteDialogComponent } from '../delete/mensaje-delete-dialog.component';

@Component({
  standalone: true,
  selector: 'jhi-mensaje',
  templateUrl: './mensaje.component.html',
  imports: [
    RouterModule,
    FormsModule,
    SharedModule,
    SortDirective,
    SortByDirective,
    DurationPipe,
    FormatMediumDatetimePipe,
    FormatMediumDatePipe,
  ],
})
export class MensajeComponent implements OnInit {
  mensajes?: IMensaje[];
  isLoading = false;

  predicate = 'id';
  ascending = true;

  constructor(
    protected mensajeService: MensajeService,
    protected activatedRoute: ActivatedRoute,
    public router: Router,
    protected sortService: SortService,
    protected modalService: NgbModal,
  ) {}

  trackId = (_index: number, item: IMensaje): number => this.mensajeService.getMensajeIdentifier(item);

  ngOnInit(): void {
    this.load();
  }

  delete(mensaje: IMensaje): void {
    const modalRef = this.modalService.open(MensajeDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.mensaje = mensaje;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        switchMap(() => this.loadFromBackendWithRouteInformations()),
      )
      .subscribe({
        next: (res: EntityArrayResponseType) => {
          this.onResponseSuccess(res);
        },
      });
  }

  load(): void {
    this.loadFromBackendWithRouteInformations().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(): void {
    this.handleNavigation(this.predicate, this.ascending);
  }

  protected loadFromBackendWithRouteInformations(): Observable<EntityArrayResponseType> {
    return combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data]).pipe(
      tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
      switchMap(() => this.queryBackend(this.predicate, this.ascending)),
    );
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const sort = (params.get(SORT) ?? data[DEFAULT_SORT_DATA]).split(',');
    this.predicate = sort[0];
    this.ascending = sort[1] === ASC;
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.mensajes = this.refineData(dataFromBody);
  }

  protected refineData(data: IMensaje[]): IMensaje[] {
    return data.sort(this.sortService.startSort(this.predicate, this.ascending ? 1 : -1));
  }

  protected fillComponentAttributesFromResponseBody(data: IMensaje[] | null): IMensaje[] {
    return data ?? [];
  }

  protected queryBackend(predicate?: string, ascending?: boolean): Observable<EntityArrayResponseType> {
    this.isLoading = true;
    const queryObject: any = {
      eagerload: true,
      sort: this.getSortQueryParam(predicate, ascending),
    };
    return this.mensajeService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(predicate?: string, ascending?: boolean): void {
    const queryParamsObj = {
      sort: this.getSortQueryParam(predicate, ascending),
    };

    this.router.navigate(['./'], {
      relativeTo: this.activatedRoute,
      queryParams: queryParamsObj,
    });
  }

  protected getSortQueryParam(predicate = this.predicate, ascending = this.ascending): string[] {
    const ascendingQueryParam = ascending ? ASC : DESC;
    if (predicate === '') {
      return [];
    } else {
      return [predicate + ',' + ascendingQueryParam];
    }
  }
}

<div>
  <h2 id="page-heading" data-cy="MensajeHeading">
    <span jhiTranslate="jhLogstashApp.mensaje.home.title">__jhiTransformTranslate__('jhLogstashApp.mensaje.home.title')</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="jhLogstashApp.mensaje.home.refreshListLabel"
          >__jhiTransformTranslate__('jhLogstashApp.mensaje.home.refreshListLabel')</span
        >
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-mensaje"
        [routerLink]="['/mensaje/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="jhLogstashApp.mensaje.home.createLabel"
          >__jhiTransformTranslate__('jhLogstashApp.mensaje.home.createLabel')</span
        >
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="mensajes?.length === 0">
    <span jhiTranslate="jhLogstashApp.mensaje.home.notFound">__jhiTransformTranslate__('jhLogstashApp.mensaje.home.notFound')</span>
  </div>

  <div class="table-responsive table-entities" id="entities" *ngIf="mensajes && mensajes.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" (sortChange)="navigateToWithComponentValues()">
          <th scope="col" jhiSortBy="id">
            <div class="d-flex">
              <span jhiTranslate="global.field.id">__jhiTransformTranslate__('global.field.id')</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="autor">
            <div class="d-flex">
              <span jhiTranslate="jhLogstashApp.mensaje.autor">__jhiTransformTranslate__('jhLogstashApp.mensaje.autor')</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="fechaPublicacion">
            <div class="d-flex">
              <span jhiTranslate="jhLogstashApp.mensaje.fechaPublicacion"
                >__jhiTransformTranslate__('jhLogstashApp.mensaje.fechaPublicacion')</span
              >
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="textoMensaje">
            <div class="d-flex">
              <span jhiTranslate="jhLogstashApp.mensaje.textoMensaje">__jhiTransformTranslate__('jhLogstashApp.mensaje.textoMensaje')</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="etiquetas">
            <div class="d-flex">
              <span jhiTranslate="jhLogstashApp.mensaje.etiquetas">__jhiTransformTranslate__('jhLogstashApp.mensaje.etiquetas')</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="autor.id">
            <div class="d-flex">
              <span jhiTranslate="jhLogstashApp.mensaje.autor">__jhiTransformTranslate__('jhLogstashApp.mensaje.autor')</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col" jhiSortBy="etiquetas.id">
            <div class="d-flex">
              <span jhiTranslate="jhLogstashApp.mensaje.etiquetas">__jhiTransformTranslate__('jhLogstashApp.mensaje.etiquetas')</span>
              <fa-icon class="p-1" icon="sort"></fa-icon>
            </div>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let mensaje of mensajes; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/mensaje', mensaje.id, 'view']">{{ mensaje.id }}</a>
          </td>
          <td>{{ mensaje.autor }}</td>
          <td>{{ mensaje.fechaPublicacion | formatMediumDatetime }}</td>
          <td>{{ mensaje.textoMensaje }}</td>
          <td>{{ mensaje.etiquetas }}</td>
          <td>
            <div *ngIf="mensaje.autor">
              <a [routerLink]="['/usuario', mensaje.autor.id, 'view']">{{ mensaje.autor.id }}</a>
            </div>
          </td>
          <td>
            <span *ngFor="let etiquetas of mensaje.etiquetas; let last = last">
              <a class="form-control-static" [routerLink]="['/etiqueta', etiquetas.id, 'view']">{{ etiquetas.id }}</a
              >{{ last ? '' : ', ' }}
            </span>
          </td>
          <td class="text-end">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/mensaje', mensaje.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">__jhiTransformTranslate__('entity.action.view')</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/mensaje', mensaje.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">__jhiTransformTranslate__('entity.action.edit')</span>
              </button>

              <button type="submit" (click)="delete(mensaje)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete"
                  >__jhiTransformTranslate__('entity.action.delete')</span
                >
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
